// i18n. The tomarigi Chrome extension delegated to browser.i18n in an extension context, and otherwise
// fetched public/_locales/<locale>/messages.json and reimplemented Chrome's getMessage semantics.
// The desktop version has no extension context, so it always does the latter (_locales is generated by scripts/gen-locales.mjs).
//
// Call-order constraint: ICON_SET_LABEL (src/perch/icon-sets.ts) and BIRD/EVENT (src/perch/stage.tsx)
// call t() at module evaluation to build their dictionaries. The await of initI18n() must have
// completed before they are imported (see src/perch/main.tsx).

import type en from "../../public/_locales/en/messages.json";

type MessagePlaceholder = { content: string; description?: string };
type MessageEntry = { message: string; placeholders?: Record<string, MessagePlaceholder> };
type MessageDict = Record<string, MessageEntry>;

// Keys are restricted to the key set of the generated en/messages.json (typos in key names are caught at compile time)
export type MessageName = keyof typeof en;

// Dictionary. initI18n() sets it here once loading completes. While initI18n() hasn't been called or all locales failed,
// it stays empty and t() just returns "", the same as Chrome
let fallbackDict: MessageDict = {};

/**
 * Resolves with the same semantics as Chrome's browser.i18n.getMessage. substitutions are supported in $1 form (1-indexed)
 * through placeholders (a single string is treated as [that string]).
 * If the key isn't in the dictionary, returns "" like Chrome.
 *
 * Restricting key to MessageName (a generated literal union) is an intentional departure from the spec.
 * Accepting a plain string would not only need a cast inside this function, it would also lose the type check
 * at the ~60 call sites (catching typos in key names at compile time) entirely
 * (verify:locales only checks the dictionaries against each other, not references from code).
 */
export function t(key: MessageName, substitutions?: string | string[]): string {
  return resolveFallback(key, substitutions);
}

/** Replacement for browser.i18n.getUILanguage. */
export function uiLanguage(): string {
  return navigator.language;
}

/**
 * Loads the dictionary. Builds candidate locales from navigator.language and, in order,
 * fetches("./_locales/<candidate>/messages.json"), using the first that succeeds
 * (the relative path is based on index.html; vite copies public/_locales to the root of dist).
 * If all fail, "en" is tried explicitly once more, and if that also fails it continues with an empty dictionary
 * (no throw — it degrades to t() just returning "").
 */
export async function initI18n(): Promise<void> {
  for (const candidate of localeCandidates(navigator.language)) {
    const dict = await tryFetchDict(candidate);
    if (dict) {
      fallbackDict = dict;
      document.documentElement.lang = candidate.replaceAll("_", "-");
      return;
    }
  }
  const en = await tryFetchDict("en");
  if (en) fallbackDict = en;
  document.documentElement.lang = "en";
}

// Builds candidates in the order specific locale → language → English, e.g. "ja-JP" → ["ja_JP", "ja", "en"].
// Chrome's _locales directory names use underscores, not hyphens
// (public/_locales/pt_BR etc.), so convert. Duplicates are removed while keeping candidate order
// (e.g. "en-US" → "en_US", "en" rather than "en_US", "en", "en". The trailing "en" is
// always included as a fallback)
function localeCandidates(lang: string): string[] {
  const normalized = lang.replaceAll("-", "_");
  const primary = normalized.split("_")[0];
  return [...new Set([normalized, primary, "en"])];
}

async function tryFetchDict(locale: string): Promise<MessageDict | null> {
  try {
    const res = await fetch(`./_locales/${locale}/messages.json`);
    if (!res.ok) return null;
    return (await res.json()) as MessageDict;
  } catch {
    return null;
  }
}

// Matches $NAME$ (case-insensitive) or $$. Per Chrome's spec, names are
// ASCII letters, digits, and underscores only
const PLACEHOLDER_RE = /\$\$|\$([A-Za-z0-9_]+)\$/g;

function resolveFallback(key: string, substitutions?: string | string[]): string {
  const entry = fallbackDict[key];
  if (!entry) return ""; // Chrome also returns "" for unknown keys (verify:locales guarantees every key exists)
  const subs = substitutions === undefined ? [] : Array.isArray(substitutions) ? substitutions : [substitutions];
  const placeholders = entry.placeholders ?? {};
  return entry.message.replace(PLACEHOLDER_RE, (whole, name?: string) => {
    if (name === undefined) return "$"; // $$ branch
    const ph = placeholders[name.toLowerCase()];
    if (!ph) return whole; // leave it untouched if there's no matching placeholder definition
    const m = /^\$(\d+)$/.exec(ph.content);
    if (!m) return whole; // leave it untouched if content isn't in $1 form
    const idx = Number(m[1]) - 1;
    return subs[idx] ?? "";
  });
}
