// Recent activity (sessionEventCache) and the persistent event log for the debug log screen
import { loadEventLog, saveEventLog } from "./settings-store";
import type { AngerJudgement, AskJudgement } from "./jev";
import type { SessionEvent } from "./session-types";
import { eventLogState, knownLogKeys, pendingLogEvents, sessionEventCache } from "./session-store";

// Birds and chicks are shown while their process is alive, regardless of idle time (docs/design.md "Removing birds
// of ended sessions"; chicks run inside the parent's claude and go away with it). This window doesn't decide
// whether anything is shown: Recent activity lists only events from this long ago (a feed of recent transitions,
// capped at MAX_EVENTS)
const RECENT_EVENTS_WINDOW_MS = 30 * 60_000;
const MAX_EVENTS = 30;
const MAX_EVENT_LOG = 500;

// The set of current SessionEvent["type"] values. Even if a retired type (formerly "harsh": removed along with
// the LLM judgement feature; generated by lib/harassment.ts) remains in the persistent log, the reading side
// (places that check against this set) safely ignores it. Existing records in IndexedDB are left as-is without
// migration, but are excluded from display and re-saving from then on
const KNOWN_EVENT_TYPES = new Set<SessionEvent["type"]>([
  "started",
  "done",
  "waiting",
  "closed",
]);

function isKnownEventType(type: string): type is SessionEvent["type"] {
  return KNOWN_EVENT_TYPES.has(type as SessionEvent["type"]);
}

function hydrateEventLog(): void {
  if (eventLogState.hydration !== "none") return;
  eventLogState.hydration = "loading";
  void (async () => {
    try {
      const saved = await loadEventLog<SessionEvent>();
      if (saved) {
        // Retired types (formerly "harsh" etc.) are excluded from re-saving and display (see KNOWN_EVENT_TYPES above)
        eventLogState.entries = saved.filter((e) => isKnownEventType(e.type));
        for (const e of eventLogState.entries) knownLogKeys.add(e.key);
      }
      eventLogState.hydration = "done";
      // Merge what was missed before restoring finished. appendToEventLog rejects known keys
      for (const event of pendingLogEvents) appendToEventLog(event);
      pendingLogEvents.length = 0;
    } catch (e) {
      // Not set to "done", to avoid the risk of overwriting existing history (saving stops for good).
      // pending will never be persisted now, so discard it (not kept in memory for the rest of this
      // session either; cacheEvent also stops adding to pending once "failed")
      console.warn("[tomarigi] failed to restore the event log", e);
      eventLogState.hydration = "failed";
      pendingLogEvents.length = 0;
    }
  })();
}

/**
 * The actual append to the persistent log. knownLogKeys prevents duplicates across all time, and only the
 * last MAX_EVENT_LOG entries are kept. assistantText (temporary field for the readout summary, max 2000
 * chars) is not written — there is no reason to pile up several KB per entry in IndexedDB for a field used
 * only for speech, so it is stripped right before persisting
 * (the in-memory sessionEventCache keeps it as-is; see cacheEvent).
 */
function appendToEventLog(event: SessionEvent): void {
  if (knownLogKeys.has(event.key)) return;
  knownLogKeys.add(event.key);
  const { assistantText: _assistantText, ...persisted } = event;
  eventLogState.entries.push(persisted);
  if (eventLogState.entries.length > MAX_EVENT_LOG) {
    const removed = eventLogState.entries.shift();
    if (removed) knownLogKeys.delete(removed.key);
  }
  eventLogState.dirty = true;
}

/**
 * Inserts into sessionEventCache are first-write-wins (a later value never overwrites the same key).
 * For event types, at comes from the transcript and never changes, so first-write-wins doesn't change behavior.
 * Only events "actually newly inserted into the Map" are also sent to the persistent log (so that even though
 * cacheEvent is called every scan, the same event isn't added to the log twice).
 */
export function cacheEvent(event: SessionEvent): void {
  if (sessionEventCache.has(event.key)) return;
  sessionEventCache.set(event.key, event);
  hydrateEventLog(); // the first call starts restoring (no-op afterwards)
  if (eventLogState.hydration === "done") {
    appendToEventLog(event);
  } else if (eventLogState.hydration !== "failed") {
    // With "failed" restoring has been given up, so stop adding to pending from then on
    // (prevents unbounded growth; appending to the persistent log is given up for this session)
    pendingLogEvents.push(event);
  }
}

/** Recent activity: events newest first, at most MAX_EVENTS */
export function recentEvents(now: number): SessionEvent[] {
  // Drop events older than RECENT_EVENTS_WINDOW_MS (every poll re-parses the tail, so this caps what accumulates
  // even after deduplication)
  for (const [key, event] of sessionEventCache) {
    if (now - event.at > RECENT_EVENTS_WINDOW_MS) sessionEventCache.delete(key);
  }
  const events = [...sessionEventCache.values()].sort((a, b) => b.at - a.at).slice(0, MAX_EVENTS);
  return events;
}

export function saveEventLogIfDirty(): void {
  // The persistent event log is written once at the end of this scan rather than on every cacheEvent (scans
  // with no new events don't write). The dirty flag can be set not only by appendToEventLog via cacheEvent but
  // also by the pending merge in hydrateEventLog
  if (eventLogState.dirty && eventLogState.hydration === "done") {
    eventLogState.dirty = false;
    void saveEventLog(eventLogState.entries).catch((e) => {
      console.warn("[tomarigi] failed to save the event log", e);
    });
  }
}

/**
 * Writes the Jev verdict to the persistent log entry of the same turn's done event (key = sessionId:at:done),
 * to see the probability in the debug log screen. Not written when the done isn't in the log yet (e.g. suppressed)
 */
export function recordAskJudgement(sessionId: string, at: number, ask: AskJudgement): void {
  const key = `${sessionId}:${at}:done`;
  const logged = eventLogState.entries.find((e) => e.key === key);
  if (!logged) return;
  logged.ask = ask;
  eventLogState.dirty = true;
}

/** Writes the abuse verdict to the persistent log entry of that message's started event (key = sessionId:at:started) */
export function recordAngerJudgement(sessionId: string, at: number, anger: AngerJudgement): void {
  const logged = eventLogState.entries.find((e) => e.key === `${sessionId}:${at}:started`);
  if (!logged) return;
  logged.anger = anger;
  eventLogState.dirty = true;
}

/** Entry point for DebugApp in the debug log screen to read the persistent event log.
 * The value type is owned by lib/session-types.ts, so this wraps loadEventLog<T> from lib/settings-store.ts.
 * Retired types (formerly "harsh" etc.) are ignored via KNOWN_EVENT_TYPES (same policy as hydrateEventLog) */
export async function loadPersistedEvents(): Promise<SessionEvent[]> {
  const saved = (await loadEventLog<SessionEvent>()) ?? [];
  return saved.filter((e) => isKnownEventType(e.type));
}
